version: '3.4'

services:
  # consent-frontend:
  #   image: ${DOCKER_REGISTRY-}consentfrontend
  #   build:
  #     context: ./consent-frontend
  #   ports:
  #     - "33000:3000"
  api:
    image: ${DOCKER_REGISTRY-}consentapi
    build:
      context: ./api
    ports:
      - "33001:3001"
