version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SqlSettings__ConnectionString=server=sql-server,1433;TrustServerCertificate=Yes;database=consentdb;user id=sa;password=Password1!
    ports:
      - "33080:8080"
      - "33081:8080"
    depends_on:
      - migrator
      - sql-server

  migrator:
     environment:
       - SqlSettings__ConnectionString=server=sql-server,1433;database=consentdb;user id=sa;password=Password1!
     build:
       context: .
       dockerfile: /src/Consent.Storage.Migrator/Dockerfile
     depends_on:
       - sql-server

  # consent-frontend:
  #   volumes:
  #     - ./consent-frontend/src:/workdir/src
  #     - ./consent-frontend/public:/workdir/public
  #     - ./consent-frontend/package.json:/workdir/package.json
  #     - ./consent-frontend/yarn.lock:/workdir/yarn.lock
  #     - ./consent-frontend/tsconfig.json:/workdir/tsconfig.json
  #   ports:
  #     - "33000:3000"

  sql-server:
    image: ${DOCKER_REGISTRY-}developmentsqlserver
    build: ./sql-server-container
    user: root
    expose:
      - 1433
    ports:
      - 31433:1433
    volumes:
      - .data/sqlserver:/var/opt/mssql/data
