version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}consentapi
    build:
      context: .
      dockerfile: src/Consent.Api/Dockerfile

#  consent-frontend:
#     image: ${DOCKER_REGISTRY-}consentfrontend
#     build:
#       context: ./consent-frontend
