version: '3.4'

services:
  consent-frontend:
    volumes:
      - ./consent-frontend/src:/workdir/src
      - ./consent-frontend/public:/workdir/public
      - ./consent-frontend/package.json:/workdir/package.json
      - ./consent-frontend/yarn.lock:/workdir/yarn.lock
      - ./consent-frontend/tsconfig.json:/workdir/tsconfig.json
