definitions:
  account.OrganizationMember:
    properties:
      role:
        $ref: '#/definitions/account.Role'
    type: object
  account.OrganizationModel:
    properties:
      created:
        type: string
      id:
        type: string
      members:
        additionalProperties:
          $ref: '#/definitions/account.OrganizationMember'
        type: object
      name:
        type: string
      removed:
        type: boolean
      updated:
        type: string
    type: object
  account.Role:
    type: object
  account.UserCreateRequest:
    properties:
      name:
        type: string
    type: object
  account.UserModel:
    properties:
      created:
        type: string
      id:
        type: string
      name:
        type: string
      removed:
        type: boolean
      updated:
        type: string
    type: object
  controllers.ComponentHealth:
    properties:
      detail:
        type: string
      isHealthy:
        type: boolean
      name:
        type: string
    type: object
  controllers.HealthResponse:
    properties:
      components:
        items:
          $ref: '#/definitions/controllers.ComponentHealth'
        type: array
    type: object
  controllers.OrganizationCreateRequest:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/account/organization:
    post:
      parameters:
      - description: Create organization
        in: body
        name: organization
        required: true
        schema:
          $ref: '#/definitions/controllers.OrganizationCreateRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.OrganizationModel'
      summary: Create an Organization
  /v1/account/organization/{id}:
    get:
      parameters:
      - description: Organization Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.OrganizationModel'
      summary: Get an Organization
  /v1/account/user:
    post:
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/account.UserCreateRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.UserModel'
      summary: Create a user
  /v1/account/user/{id}:
    get:
      parameters:
      - description: User Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.UserModel'
      summary: Get an user
  /v1/health:
    get:
      description: Get component by component health status
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.HealthResponse'
      summary: Get Health
swagger: "2.0"
